<!-- Message de notification -->

<!-- Code HTML à écrire -->

<!-- Liste des produits alimentaires -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <tr>
            <td><img src="/coca.jpg" alt="Coca-Cola"></td>
            <td>
                <strong>Coca-Cola</strong>
                <p>Mmmm, le Coca-Cola avec 10 morceaux de sucres et tout plein de caféine !</p>
            </td>
            <td class="number"><strong>3.00</strong> €</td>
        </tr>
        <tr>
            <td><img src="bagel_thon.jpg" alt="Bagel Thon"></td>
            <td>
                <strong>Bagel Thon</strong>
                <p>Notre bagel est constitué d'un pain moelleux avec des grains de sésame et du thon albacore, accompagné de feuilles de salade fraîche du jour  et d'une sauce renversante :-)</p>
            </td>
            <td class="number"><strong>5.50</strong> €</td>
        </tr>
        <tr>
            <td><img src="bacon_cheeseburger.jpg" alt="Bacon Cheeseburger"></td>
            <td>
                <strong>Bacon Cheeseburger</strong>
                <p>Ce délicieux cheeseburger contient un steak haché viande française de 150g ainsi que d'un buns grillé juste comme il faut, le tout accompagné de frites fraîches maison !</p>
            </td>
            <td class="number"><strong>12.50</strong> €</td>
        </tr>
        <tr>
            <td><img src="carrot_cake.jpg" alt="Carrot Cake"></td>
            <td>
                <strong>Carrot Cake</strong>
                <p>Le carrot cake maison ravira les plus gourmands et les puristes : tous les ingrédients sont naturels ! À consommer sans modération</p>
            </td>
            <td class="number"><strong>6.75</strong> €</td>
        </tr>
        <tr>
            <td><img src="chocolate_donut.jpg" alt="Donut Chocolat"></td>
            <td>
                <strong>Donut Chocolat</strong>
                <p>Les donuts sont fabriqués le matin même et sont recouvert d'une délicieuse sauce au chocolat !</p>
            </td>
            <td class="number"><strong>6.20</strong> €</td>
        </tr>
        <tr>
            <td><img src="drpepper.jpg" alt="Dr. Pepper"></td>
            <td>
                <strong>Dr. Pepper</strong>
                <p>Son goût sucré avec de l'amande vous ravira !</p>
            </td>
            <td class="number"><strong>2.90</strong> €</td>
        </tr>
        <tr>
            <td><img src="milkshake.jpg" alt="Milkshake"></td>
            <td>
                <strong>Milkshake</strong>
                <p>Notre milkshake bien crémeux contient des morceaux d'Oréos et est accompagné de crème chantilly et de smarties en guise de topping. Il éblouira vos papilles !</p>
            </td>
            <td class="number"><strong>5.35</strong> €</td>
        </tr>
        <tr>
            <td><img src="frites.jpg" alt="Frites"></td>
            <td>
                <strong>Frites</strong>
                <p>Aaaaaah ces merveilleux bâtonnets de pomme de terre qui nous régalent depuis qu'on est petit. Venez déguster les notres, elles sont faites maison !</p>
            </td>
            <td class="number"><strong>2.50</strong> €</td>
        </tr>
        <tr>
            <td><img src="hot_dog.png" alt="Hot-dog"></td>
            <td>
                <strong>Hot-dog</strong>
                <p>Le typique sandwitch américain avec sa saucisse cuite accompagnée de ketchup, moutarde, oignons ou encore une bonne mayonnaise dont nous avons le secret.</p>
            </td>
            <td class="number"><strong>3.50</strong> €</td>
        </tr>
    </tbody>
</table>