<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>My traducteur template.phtml</title>
	</head>
	<body>
		<header>
			<h1>Traducteur</h1>
		</header>
	<main>
		<form method="post" action="#">
			<input type="text" name="word">
			<select name="direction" id="direction">
				<option value="toEnglish">Traduire de français à anglais</option>
				<option value="toFrench">Traduire de anglais à français</option>
			</select>
			<input type="submit" value="submit">
		</form>
	</main>
	<footer>
	</footer>
	</body>
</html>