<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Encore un Blog ?! #nonMaisAllo</title>
    <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="index.css">
</head>
<body>
    <!-- En-tête commune de l'application -->
    <header class="blog-header">
        <h1><a href="index.php"><i class="fa fa-microphone"></i> Encore un Blog ?! #nonMaisAllo</a></h1>
        <nav>
            <a href="admin.php"><i class="fa fa-cogs"></i> Administration</a>
        </nav>
    </header>
    <main>
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <h2><i class="fa fa-cogs"></i> Panneau d'administration</h2>
    <nav>
        <a href="newarticle.php">Rédiger un nouvel article</a>
    </nav>
    <table>
        <caption>Liste des articles</caption>
        <thead>
            <tr>
                <th>Titre</th>
                <th>Article</th>
                <th>Auteur</th>
                <th>Catégorie</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($admart as $index => $ligne) { ?>
            <tr>
                <td><?=$admart[$index]["Title"];?></td>
                <td><?=$admart[$index]["Contents"];?></td>
                <td><?=$admart[$index]["FirstName"];?> <?=$admart[$index]["LastName"];?></td>
                <td><?=$admart[$index]["Name"];?></td>
                <td>
                    <a class="edit" href="editarticle.php?id_post=<?=$ligne["Id"];?>"><i class="fa fa-pencil"></i></a>
                    <a class="remove" href="deletearticle.php?id_post=<?=$ligne["Id"];?>"><i class="fa fa-remove"></i></a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    </main>
    <!-- Pied de page commun de l'application -->
    <footer class="blog-footer">
        <small>Le blog des élèves de la 3W Academy</small>
    </footer>
</body>
</html>

