<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <link rel= "stylesheet" href= "font-awesome/css/font-awesome.min.css" >
  <link href="https://fonts.googleapis.com/css?family=Candal|Open+Sans" rel="stylesheet"> 
  <link href="index.css" rel="stylesheet" media="all" type="text/css">
  <title>Acceuil 4/5</title>
</head>
<body>
  <header>
    <h1><i class="fa fa-microphone" aria-hidden="true"><a href="#">Encore un blog ?! #Nonmaisallo</a></i></h1>
    <div class="admin">
    <i class="fa fa-cogs" aria-hidden="true"></i><a href="admin.php">Administration</a>
    </div>
  </header>
  <main>
    <h2><i class="fa fa-home" aria-hidden="true"></i>Accueil</h2>
    <?php foreach($adrequete as $index => $ligne) { ?>
    <article>
      <!--Titre de l'article-->
      <h3><?=$adrequete[$index]["Title"]?></a></h3>
      <!--Contenu de l'article-->
      <p><?=$adrequete[$index]["Contents"]?></p>
      <!--Footer de l'article-->
      <p>Rédigé par <?=$adrequete[$index]["FirstName"]?> <?=$adrequete[$index]["LastName"]?> le <?=$adrequete[$index]["CreationTimestamp"]?></p>
    </article>
    <?php } ?>
  </main>
  <footer>
    <p>Le blog des élèves de la 3W Academy</p>
  </footer>
</body>
</html>

29090109 698470589