	<ul>
		<input type="hidden" name="idusers" value="<?= $idusers; ?>">
		<li class="form-group">
			<img id="portrait" src="">
		</li>
		<li class="form-group">
			<label for="pseudo">Pseudo</label>
			<span id="pseudo" class="form-control"><?= $pseudo; ?></span>
		</li>
		<li class="form-group">
			<label for="prenom">Prénom</label>
			<span id="prenom" class="form-control"><?= $prenom; ?></span>
		</li>
		<li class="form-group">
			<label for="nom">Nom</label>
			<span id="nom" class="form-control"><?= $nom; ?></span>
		</li>
		<li class="form-group">
			<label for="mail">Mail</label>
			<span id="mail" class="form-control"><?= $mail; ?></span>
		</li>
		<li class="form-group">
			<label for="mobile">Mobile</label>
			<span id="mobile" class="form-control"><?= $mobile; ?></span>
		</li>
		<li>
			<a class="btn btn-info" href="index.php?page=modifier">Modifier</a>
		</li>
	</ul>
