<form method="post" action="index.php?page=new_account">
	<ul>
		<input type="hidden" name="idusers" value="<?= $idusers; ?>">
		<li class="form-group">
			<label for="pseudo">Pseudo</label>
			<input type="text" name="pseudo" id="pseudo" class="form-control" value="<?= $pseudo; ?>">
		</li>
		<li class="form-group">
			<label for="prenom">Prénom</label>
			<input type="text" name="prenom" id="prenom" class="form-control" value="<?= $prenom; ?>">
		</li>
		<li class="form-group">
			<label for="nom">Nom</label>
			<input type="text" name="nom" id="nom" class="form-control" value="<?= $nom; ?>">
		</li>
		<li class="form-group">
			<label for="mail">Mail</label>
			<input type="text" name="mail" id="mail" class="form-control" value="<?= $mail; ?>">
		</li>
		<li class="form-group">
			<label for="mobile">Mobile</label>
			<input type="text" name="mobile" id="mobile" class="form-control" value="<?= $mobile; ?>">
		</li>
		<li class="form-group">
			<label for="pass[]">Pass</label>
			<input type="password" name="pass[]" id="pass[]" class="form-control" value="<?= $pass; ?>">
		</li>
		<li class="form-group">
			<label for="pass[]">Pass</label>
			<input type="password" name="pass[]" id="pass[]" class="form-control" value="<?= $pass; ?>">
		</li>
		<li>
			<input type="submit" name="boutton" value="Créer" class="btn btn-default">
		</li>
	</ul>
</form>