<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Encore un Formulaire ?! #nonMaisAllo</title>

    <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="vue/css/reset.css">
    <link rel="stylesheet" href="vue/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="vue/css/font-awesome.min.css">

    <!-- Polices -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kumar+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">

    <!-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="vue/css/blog-main.css">
    <link rel="stylesheet" href="vue/css/blog-theme.css">
    <link rel="stylesheet" href="vue/css/ui-button.css">
    <link rel="stylesheet" href="vue/css/ui-form.css">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script> -->
</head>
<body>
    <!-- En-tête commune de l'application -->
    <header class="blog-header">
        <h1><a href="?page=index"><i class="fa fa-google-wallet"></i> Formulaire d'inscription</a></h1>
        <nav>
            <a href="?page=admin"><i class="fa fa-firefox"></i> Administration</a>
        </nav>
    </header>

    <main>
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <?php include $page.'.phtml' ?>
    </main>

    <!-- Pied de page commun de l'application -->
    <footer class="blog-footer">
        <small>Le blog des élèves de la 3W Family</small>
    </footer>
</body>
</html>