<form class="generic-form" action="" method="">
    <fieldset>
        <legend>Recherche de clients</legend>
        <ul>
            <li>
                <label for="country">Pays :</label>
                <input id="country" name="country" type="text">
            </li>
            <li>
                <button class="button button-primary" type="submit">Rechercher</button>
            </li>
        </ul>
    </fieldset>
</form>
<footer>
    <hr>
    <ul class="link-list">
        <li><a class="button button-primary" href="../">Accueil</a></li>
    </ul>
</footer>
