<!-- Message de notification -->

<!-- Code HTML à écrire -->
<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
    	<?php
    		foreach ($carte as $key => $value) { ?>
    			<tr>
    				<td><img src="<?= $wwwUrl;?>/images/meals/<?= $value['Photo'];?>"></td>
    				<td><?= $value['Description'];?></td>
    				<td><?= number_format($value['SalePrice'], 2);?> €</td>
    			</tr>
    	<?php } ?>

    </tbody>
</table>