<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>TEMPLATE.PHTML</title>
</head>
<body>
	<h1>NOM DE CODE : E25</h1>
		<form method="POST" action="recup.php">
			<br>
			First name :<br>
		  	<input type="text" name="firstname"><br>
		  	Nombre :<br>
		  	<input type="number" name="nombre"><br>
			<input type="radio" name="gender" value="skorpion" checked> Skorpion<br>
			<input type="radio" name="gender" value="e25"> E25<br>
		  	<input type="radio" name="gender" value="other"> Other<br>
		  	<input type="submit" value="submit"><br>
		  	<br>
		</form>
		<?php
			if($carre !== null){
				echo '<p> Le carré de: '.$nombre.' est : '.$carre.'</p>';
			}
		?>
</body>
</html>