<!DOCTYPE html>
<html>
<head>
	<title>Formulaire d'inscription</title>
</head>
<body>
	<form method="POST" action="../../modele/blog/action_page.php">
		<fieldset>
		    <legend>Formulaire d'inscription :</legend>
		    Pseudo :<br>
		    <input type="text" name="pseudo"><br><br>
		    Prenom :<br>
		    <input type="text" name="prenom"><br><br>
		    Nom :<br>
		    <input type="text" name="nom"><br><br>
		    Mail :<br>
		    <input type="text" name="email"><br><br>
		    Mobile :<br>
		    <input type="text" name="tel"><br><br>
		    Pass :<br>
		    <input type="password" name="password"><br><br>
		    Pass :<br>
		    <input type="password" name="password2"><br><br>
		    <input type="submit" value="Submit">
		</fieldset>
	</form>
</body>
</html>