<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>PHP</title>
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="css/painter.css">
</head>
<body>
    <h1>3WA Painter</h1>
    Test class

    <p><?= $fromages->getValue(); ?></p>
    <p><?= $fromages->affiche(); ?></p>
    <p><?= $fromages->dessine($dessin); ?></p>
    <p>----------------------------</p>
    <p><?= $boissons->getValue(); ?></p>
    <p><?= $boissons->affiche(); ?></p>
    <p><?= $boissons->vendeur(); ?></p>
    <p><?= $boissons->dessine($dessin); ?></p>

</body>
</html>